version: "3"

services:
  notebook:
    build:
      context: .
      dockerfile: ./dockerfiles/python/Dockerfile
    ports:
      - "8888:8888" #jupyter
      - "4040:4040" #spark job
    volumes:
      - ./notebooks:/app/dags
    restart: unless-stopped
    command: sh /jupyter_run.sh

  airflow:
    build:
      context: .
      dockerfile: ./dockerfiles/airflow/Dockerfile
    environment:
      - AIRFLOW_HOME=/app
    ports:
      - "8000:8000"
    # extra_hosts:
    #   - ""
    # dns:
    #   - 111
    volumes:
      - ./dags:/app/dags
    restart: unless-stopped
    command: sh /airflow_run.sh

  spark_yarn:
    build:
      context: .
      dockerfile: ./dockerfiles/spark_yarn/Dockerfile
    restart: unless-stopped
    command: sh /run.sh
